config/routes.rb
Rails.application.routes.draw do
  root 'articles#index'

  resources :articles do
    resources :comments
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  validates :title, presence: true
  validates :body, presence: true, length: { minimum: 10 }

  has_many :comments, dependent: :destroy
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  http_basic_authenticate_with name: 'dhh', password: 'secret', only: :destroy

  def index
    @articles = Article.all
  end

  def show
    @article = Article.find(params[:id])
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)

    if @article.save
      redirect_to @article
    else
      render :new
    end
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])

    if @article.update(article_params)
      redirect_to @article
    else
      render :edit
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    redirect_to root_path
  end

  private
    def article_params
      params.require(:article).permit(:title, :body)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  http_basic_authenticate_with name: 'dhh', password: 'secret', only: :destroy

  def create
    @article = Article.find(params[:article_id])
    @comment = @article.comments.create(comment_params)
    redirect_to article_path(@article)
  end

  def destroy
    @article = Article.find(params[:article_id])
    @comment = @article.comments.find(params[:id])
    @comment.destroy
    redirect_to article_path(@article)
  end

  private
  def comment_params
    params.require(:comment).permit(:author, :body)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/articles/_form.html.erb
<%= form_with model: article do |form| %>
  <div class="mb-3">
    <%= form.label :title, class: 'form-label' %>
    <%= form.text_field :title, class: 'form-control' %>
    <% @article.errors.full_messages_for(:title).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div class="mb-3">
    <%= form.label :body, class: 'form-label' %>
    <%= form.text_area :body, class: 'form-control' %>
    <% @article.errors.full_messages_for(:body).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div class="mb-3">
    <%= form.submit class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Edit Article</h1>

<%= render 'form', article: @article %>

app/views/articles/index.html.erb
<h2>Articles</h2>


<% @articles.each do |article| %>
  <div class="col-xl-3 col-lg-4 col-md-6 col-sm-12 col-xs-12 mb-3">
    <div class="card" style="width: 18rem;">
      <div class="card-body">
        <h5 class="card-title"><%= article.title%></h5>
        <h6 class="card-subtitle mb-2 text-muted"><%= article.created_at %></h6>
        <p class="card-text"><%= article.body %></p>
        <%= link_to 'Detail', article, class: 'btn btn-primary float-right' %>
      </div>
    </div>
  </div>
<% end %>

app/views/articles/new.html.erb
<h1>New Article</h1>

<%= render 'form', article: @article %>

app/views/articles/show.html.erb
<h1><%= @article.title %></h1>

<p><%= @article.body %></p>

<div class="pb-3">
  <i class="fa fa-pen" aria-hidden="true"> <%= link_to "Edit", edit_article_path(@article) %></i>
  <i class="fa fa-trash" aria-hidden="true"> <%= link_to "Delete", article_path(@article), method: :delete, data: { confirm: "Are you sure?" } %></i>
</div>

<h2>Comments:</h2>
<%= render @article.comments %>

<h2>Add a comment:</h2>
<%= render 'comments/form' %>

app/views/comments/_comment.html.erb
<div class="mb-3">
  <strong>Author:</strong>
  <%= comment.author %>
</div>

<div class="mb-3">
  <strong>Comment:</strong>
  <%= comment.body %>
</div>
<i class="fa fa-trash pb-3" aria-hidden="true"> <%= link_to 'Delete comment', [comment.article, comment], method: :delete, data: {confirm: "Are you sure?"} %></i>
<hr>

app/views/comments/_form.html.erb
<%= form_with model: [ @article, @article.comments.build ] do |form| %>
  <div class="mb-3">
    <%= form.label :author, class: 'form-label' %>
    <%= form.text_field :author, class: 'form-control' %>
  </div>

  <div class="mb-3">
    <%= form.label :body, class: 'form-label' %>
    <%= form.text_area :body, class: 'form-control' %>
  </div>

  <div class="mb-3">
    <%= form.submit class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsBlog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
          <%= link_to 'Rails Blog', root_path, class: 'navbar-brand' %>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
              <li class="nav-item">
                <% if request.original_url == new_article_url %>
                  <%= link_to 'New article', new_article_path, class: 'nav-link active' %>
                <% else %>
                  <%= link_to 'New article', new_article_path, class: 'nav-link' %>
                <% end %>
              </li>
            </ul>
          </div>
        </div>
      </nav>
      <div class="row align-items-start">
        <%= yield %>
      </div>
    </div>
  </body>
</html>